# Generated by Django 5.1.7 on 2025-03-25 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estoque', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estoqueprodutos',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estoque_produtos', to='usuarios.empresa', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='movimentacoesestoque',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimentacoes_estoque', to='estoque.estoqueprodutos', verbose_name='Produto'),
        ),
        migrations.AlterUniqueTogether(
            name='estoqueprodutos',
            unique_together={('empresa', 'nome')},
        ),
    ]
