# Generated by Django 5.1.7 on 2025-03-24 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relatorios', '0001_create_resumo_folha_pagamento_view'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resumofolhapagamento',
            options={'managed': False, 'ordering': ['empresa', 'funcionario', 'data_pagamento'], 'verbose_name': 'Resumo da Folha de Pagamento', 'verbose_name_plural': 'Resumos da Folha de Pagamento'},
        ),
    ]
