# Generated by Django 5.1.7 on 2025-03-25 20:15

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FolhaPagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_pagamento', models.DateField(verbose_name='Data de Pagamento')),
                ('salario_bruto', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Salário Bruto')),
                ('salario_liquido', models.DecimalField(decimal_places=2, editable=False, max_digits=10, verbose_name='Salário Líquido')),
                ('inss_empresa', models.DecimalField(decimal_places=2, editable=False, max_digits=10, verbose_name='INSS Empresa (8%)')),
                ('inss_funcionario', models.DecimalField(decimal_places=2, editable=False, max_digits=10, verbose_name='INSS Funcionário (3%)')),
                ('irt', models.DecimalField(decimal_places=2, editable=False, max_digits=10, verbose_name='IRT')),
                ('horas_extras', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Horas Extras')),
                ('bonus', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Bônus')),
                ('comissoes', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Comissões')),
                ('subsidios', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Subsídios')),
                ('faltas', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Faltas')),
                ('atrasos', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Atrasos')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
            ],
            options={
                'verbose_name': 'Folha de Pagamento',
                'verbose_name_plural': 'Folhas de Pagamento',
                'ordering': ['-data_pagamento', 'funcionario'],
            },
        ),
        migrations.CreateModel(
            name='Funcionarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome do Funcionário')),
                ('nif', models.CharField(max_length=20, unique=True, verbose_name='NIF')),
                ('cargo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cargo')),
                ('departamento', models.CharField(blank=True, max_length=100, null=True, verbose_name='Departamento')),
                ('data_admissao', models.DateField(verbose_name='Data de Admissão')),
                ('tipo_contrato', models.CharField(choices=[('Efetivo', 'Efetivo'), ('Temporário', 'Temporário'), ('Estágio', 'Estágio')], max_length=50, verbose_name='Tipo de Contrato')),
                ('salario_base', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Salário Base')),
                ('banco', models.CharField(blank=True, max_length=100, null=True, verbose_name='Banco')),
                ('nib', models.CharField(blank=True, max_length=34, null=True, verbose_name='NIB')),
                ('status', models.CharField(choices=[('Ativo', 'Ativo'), ('Inativo', 'Inativo')], default='Ativo', max_length=10, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
            ],
            options={
                'verbose_name': 'Funcionário',
                'verbose_name_plural': 'Funcionários',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='RecibosSalario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo_pdf', models.FileField(blank=True, null=True, upload_to='recibos/%Y/%m/', verbose_name='Arquivo PDF')),
                ('data_envio', models.DateTimeField(blank=True, null=True, verbose_name='Data de Envio')),
                ('email_destinatario', models.EmailField(max_length=100, validators=[django.core.validators.EmailValidator()], verbose_name='Email do Destinatário')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
            ],
            options={
                'verbose_name': 'Recibo de Salário',
                'verbose_name_plural': 'Recibos de Salário',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BeneficiosSubsidios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Alimentação', 'Alimentação'), ('Transporte', 'Transporte'), ('Férias', 'Férias'), ('13º', '13º Salário'), ('Subsídio de Natal', 'Subsídio de Natal'), ('Subsídio de Férias', 'Subsídio de Férias'), ('Subsídio de Alimentação', 'Subsídio de Alimentação'), ('Subsídio de Transporte', 'Subsídio de Transporte'), ('Outros', 'Outros')], max_length=50, verbose_name='Tipo de Benefício')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Valor')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('folha_pagamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rh.folhapagamento', verbose_name='Folha de Pagamento')),
            ],
            options={
                'verbose_name': 'Benefício/Subsídio',
                'verbose_name_plural': 'Benefícios e Subsídios',
                'ordering': ['tipo'],
            },
        ),
    ]
