# Generated by Django 5.1.7 on 2025-03-24 21:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subscriptions', '0002_empresas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome do Funcionário')),
                ('nif', models.CharField(max_length=20, unique=True, verbose_name='NIF')),
                ('cargo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cargo')),
                ('departamento', models.CharField(blank=True, max_length=100, null=True, verbose_name='Departamento')),
                ('data_admissao', models.DateField(verbose_name='Data de Admissão')),
                ('tipo_contrato', models.CharField(choices=[('Efetivo', 'Efetivo'), ('Temporário', 'Temporário'), ('Estágio', 'Estágio')], max_length=50, verbose_name='Tipo de Contrato')),
                ('salario_base', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Salário Base')),
                ('banco', models.CharField(blank=True, max_length=100, null=True, verbose_name='Banco')),
                ('nib', models.CharField(blank=True, max_length=34, null=True, verbose_name='NIB')),
                ('status', models.CharField(choices=[('Ativo', 'Ativo'), ('Inativo', 'Inativo')], default='Ativo', max_length=10, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscriptions.empresas', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Funcionário',
                'verbose_name_plural': 'Funcionários',
                'ordering': ['nome'],
                'unique_together': {('empresa', 'nif')},
            },
        ),
    ]
