# Generated by Django 5.1.7 on 2025-03-25 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rh', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionarios',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.empresa', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='folhapagamento',
            name='funcionario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rh.funcionarios', verbose_name='Funcionário'),
        ),
        migrations.AddField(
            model_name='recibossalario',
            name='folha_pagamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rh.folhapagamento', verbose_name='Folha de Pagamento'),
        ),
        migrations.AlterUniqueTogether(
            name='funcionarios',
            unique_together={('empresa', 'nif')},
        ),
        migrations.AlterUniqueTogether(
            name='folhapagamento',
            unique_together={('funcionario', 'data_pagamento')},
        ),
        migrations.AlterUniqueTogether(
            name='recibossalario',
            unique_together={('folha_pagamento',)},
        ),
    ]
