# Generated by Django 5.1.7 on 2025-03-24 21:29

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FolhaPagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_pagamento', models.DateField(verbose_name='Data de Pagamento')),
                ('salario_bruto', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Salário Bruto')),
                ('salario_liquido', models.DecimalField(decimal_places=2, editable=False, max_digits=10, verbose_name='Salário Líquido')),
                ('inss_empresa', models.DecimalField(decimal_places=2, editable=False, max_digits=10, verbose_name='INSS Empresa (8%)')),
                ('inss_funcionario', models.DecimalField(decimal_places=2, editable=False, max_digits=10, verbose_name='INSS Funcionário (3%)')),
                ('irt', models.DecimalField(decimal_places=2, editable=False, max_digits=10, verbose_name='IRT')),
                ('horas_extras', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Horas Extras')),
                ('bonus', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Bônus')),
                ('comissoes', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Comissões')),
                ('subsidios', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Subsídios')),
                ('faltas', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Faltas')),
                ('atrasos', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Atrasos')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rh.funcionarios', verbose_name='Funcionário')),
            ],
            options={
                'verbose_name': 'Folha de Pagamento',
                'verbose_name_plural': 'Folhas de Pagamento',
                'ordering': ['-data_pagamento', 'funcionario'],
                'unique_together': {('funcionario', 'data_pagamento')},
            },
        ),
    ]
