# Generated by Django 5.1.7 on 2025-03-24 21:31

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0002_folhapagamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='BeneficiosSubsidios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Alimentação', 'Alimentação'), ('Transporte', 'Transporte'), ('Férias', 'Férias'), ('13º', '13º Salário'), ('Subsídio de Natal', 'Subsídio de Natal'), ('Subsídio de Férias', 'Subsídio de Férias'), ('Subsídio de Alimentação', 'Subsídio de Alimentação'), ('Subsídio de Transporte', 'Subsídio de Transporte'), ('Outros', 'Outros')], max_length=50, verbose_name='Tipo de Benefício')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Valor')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('folha_pagamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rh.folhapagamento', verbose_name='Folha de Pagamento')),
            ],
            options={
                'verbose_name': 'Benefício/Subsídio',
                'verbose_name_plural': 'Benefícios e Subsídios',
                'ordering': ['tipo'],
            },
        ),
    ]
