# Generated by Django 5.1.7 on 2025-03-24 21:34

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0003_beneficiossubsidios'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecibosSalario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo_pdf', models.FileField(blank=True, null=True, upload_to='recibos/%Y/%m/', verbose_name='Arquivo PDF')),
                ('data_envio', models.DateTimeField(blank=True, null=True, verbose_name='Data de Envio')),
                ('email_destinatario', models.EmailField(max_length=100, validators=[django.core.validators.EmailValidator()], verbose_name='Email do Destinatário')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('folha_pagamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rh.folhapagamento', verbose_name='Folha de Pagamento')),
            ],
            options={
                'verbose_name': 'Recibo de Salário',
                'verbose_name_plural': 'Recibos de Salário',
                'ordering': ['-created_at'],
                'unique_together': {('folha_pagamento',)},
            },
        ),
    ]
