# Generated by Django 5.1.7 on 2025-03-25 01:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='tipo',
            field=models.CharField(choices=[('super_admin', 'Super Administrador'), ('admin_empresa', 'Administrador da Empresa'), ('usuario', 'Usuário')], default='usuario', max_length=20),
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=10, verbose_name='Ação')),
                ('path', models.CharField(max_length=255, verbose_name='Caminho')),
                ('ip_address', models.GenericIPAddressField(verbose_name='Endereço IP')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Data/Hora')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Atividade do Usuário',
                'verbose_name_plural': 'Atividades dos Usuários',
                'ordering': ['-timestamp'],
            },
        ),
    ]
