# Generated by Django 5.1.7 on 2025-03-25 20:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscricao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ativa', 'Ativa'), ('pendente', 'Pendente'), ('cancelada', 'Cancelada'), ('expirada', 'Expirada')], default='pendente', max_length=20)),
                ('periodo', models.CharField(choices=[('mensal', 'Mensal'), ('anual', 'Anual')], default='mensal', max_length=10)),
                ('data_inicio', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_fim', models.DateTimeField()),
                ('ultima_fatura', models.DateTimeField(blank=True, null=True)),
                ('proxima_fatura', models.DateTimeField()),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('usuarios_ativos', models.IntegerField(default=0)),
                ('notas', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Subscrição',
                'verbose_name_plural': 'Subscrições',
                'ordering': ['-data_inicio'],
            },
        ),
        migrations.CreateModel(
            name='PacoteSubscricao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('tipo', models.CharField(choices=[('basico', 'Básico'), ('profissional', 'Profissional'), ('enterprise', 'Enterprise')], default='basico', max_length=20)),
                ('descricao', models.TextField()),
                ('preco_mensal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('preco_anual', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_usuarios', models.IntegerField(default=5)),
                ('max_armazenamento_gb', models.IntegerField(default=5)),
                ('recursos_incluidos', models.JSONField(default=dict)),
                ('ativo', models.BooleanField(default=True)),
                ('periodo_teste_dias', models.IntegerField(default=15)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('permissoes', models.ManyToManyField(related_name='pacotes', to='auth.permission')),
            ],
            options={
                'verbose_name': 'Pacote de Subscrição',
                'verbose_name_plural': 'Pacotes de Subscrição',
                'ordering': ['preco_mensal'],
            },
        ),
    ]
