# Generated by Django 5.1.7 on 2025-03-25 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assinaturas', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscricao',
            name='empresa',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscricao', to='usuarios.empresa'),
        ),
        migrations.AddField(
            model_name='subscricao',
            name='pacote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='assinaturas.pacotesubscricao'),
        ),
    ]
