# Generated by Django 5.1.7 on 2025-03-25 20:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pos', '0001_initial'),
        ('usuarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.empresa', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='venda',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vendas_criadas', to=settings.AUTH_USER_MODEL, verbose_name='Usuário Criador'),
        ),
        migrations.AddField(
            model_name='venda',
            name='usuario_atual',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vendas_atuais', to=settings.AUTH_USER_MODEL, verbose_name='Usuário Atual'),
        ),
        migrations.AddField(
            model_name='pagamento',
            name='venda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos', to='pos.venda', verbose_name='Venda'),
        ),
        migrations.AddField(
            model_name='itemvenda',
            name='venda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='pos.venda', verbose_name='Venda'),
        ),
    ]
