# Generated by Django 5.1.7 on 2025-03-25 20:45

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da Conta')),
                ('tipo', models.CharField(choices=[('conta_corrente', 'Conta Corrente'), ('poupanca', 'Conta Poupança'), ('investimento', 'Conta Investimento'), ('cartao_credito', 'Cartão de Crédito'), ('outros', 'Outros')], max_length=20, verbose_name='Tipo de Conta')),
                ('banco', models.CharField(max_length=100, verbose_name='Banco')),
                ('agencia', models.CharField(max_length=10, verbose_name='Agência')),
                ('numero', models.CharField(max_length=20, verbose_name='Número da Conta')),
                ('saldo_inicial', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Saldo Inicial')),
                ('saldo_atual', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Saldo Atual')),
                ('ativa', models.BooleanField(default=True, verbose_name='Conta Ativa')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Conta',
                'verbose_name_plural': 'Contas',
                'ordering': ['nome'],
                'unique_together': {('empresa', 'nome')},
            },
        ),
    ]
