# Generated by Django 5.1.7 on 2025-03-24 21:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome da Empresa')),
                ('nif', models.CharField(max_length=20, unique=True, verbose_name='NIF')),
                ('endereco', models.TextField(blank=True, null=True, verbose_name='Endereço')),
                ('contato', models.CharField(blank=True, max_length=50, null=True, verbose_name='Contato')),
                ('email', models.EmailField(blank=True, max_length=100, null=True, verbose_name='E-mail')),
                ('logo', models.CharField(blank=True, max_length=255, null=True, verbose_name='Caminho do Logo')),
                ('data_inicio_assinatura', models.DateField(blank=True, null=True, verbose_name='Data de Início da Assinatura')),
                ('data_fim_assinatura', models.DateField(blank=True, null=True, verbose_name='Data de Fim da Assinatura')),
                ('status', models.CharField(choices=[('Ativo', 'Ativo'), ('Inativo', 'Inativo'), ('Suspenso', 'Suspenso')], default='Ativo', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('plano_assinatura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='subscriptions.planosassinatura', verbose_name='Plano de Assinatura')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'ordering': ['nome'],
            },
        ),
    ]
