# Generated by Django 5.1.7 on 2025-03-24 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
        ('subscriptions', '0002_empresas'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='clientes',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='clientes',
            name='nif',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='NIF'),
        ),
        migrations.AlterUniqueTogether(
            name='clientes',
            unique_together={('empresa', 'nif')},
        ),
    ]
