# Generated by Django 5.1.7 on 2025-03-25 01:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estoque', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimentacoesEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Entrada', 'Entrada'), ('Saída', 'Saída')], max_length=10, verbose_name='Tipo de Movimentação')),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Quantidade')),
                ('data', models.DateTimeField(auto_now_add=True, verbose_name='Data da Movimentação')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes_controle', to='estoque.estoqueprodutos', verbose_name='Produto')),
            ],
            options={
                'verbose_name': 'Movimentação de Estoque',
                'verbose_name_plural': 'Movimentações de Estoque',
                'ordering': ['-data'],
            },
        ),
    ]
