# Generated by Django 5.1.7 on 2025-03-24 21:38

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subscriptions', '0002_empresas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome do Cliente')),
                ('nif', models.CharField(blank=True, max_length=20, null=True, verbose_name='NIF')),
                ('endereco', models.TextField(blank=True, null=True, verbose_name='Endereço')),
                ('contato', models.CharField(blank=True, max_length=50, null=True, verbose_name='Contato')),
                ('email', models.EmailField(blank=True, max_length=100, null=True, validators=[django.core.validators.EmailValidator()], verbose_name='Email')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscriptions.empresas', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['nome'],
                'unique_together': {('empresa', 'nif')},
            },
        ),
    ]
