# Generated by Django 5.1.7 on 2025-03-25 01:34

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome do Cliente')),
                ('nif', models.CharField(blank=True, max_length=20, null=True, verbose_name='NIF')),
                ('endereco', models.TextField(blank=True, null=True, verbose_name='Endereço')),
                ('contato', models.CharField(blank=True, max_length=50, null=True, verbose_name='Contato')),
                ('email', models.EmailField(blank=True, max_length=100, null=True, validators=[django.core.validators.EmailValidator()], verbose_name='Email')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['nome'],
                'unique_together': {('empresa', 'nif')},
            },
        ),
        migrations.CreateModel(
            name='Faturas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_emissao', models.DateField(verbose_name='Data de Emissão')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Valor Total')),
                ('status', models.CharField(choices=[('PAGA', 'Paga'), ('PENDENTE', 'Pendente'), ('CANCELADA', 'Cancelada')], default='PENDENTE', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='faturacao.clientes', verbose_name='Cliente')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Fatura',
                'verbose_name_plural': 'Faturas',
                'ordering': ['-data_emissao'],
            },
        ),
        migrations.CreateModel(
            name='Produtos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, verbose_name='Código')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição')),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Preço Unitário')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'ordering': ['descricao'],
            },
        ),
        migrations.CreateModel(
            name='ItensFatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantidade')),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Preço Unitário')),
                ('subtotal', models.DecimalField(decimal_places=2, editable=False, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Subtotal')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('fatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='faturacao.faturas', verbose_name='Fatura')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='faturacao.produtos', verbose_name='Produto')),
            ],
            options={
                'verbose_name': 'Item da Fatura',
                'verbose_name_plural': 'Itens da Fatura',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Proformas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_emissao', models.DateField(verbose_name='Data de Emissão')),
                ('valor_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Valor Total')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='faturacao.clientes', verbose_name='Cliente')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Proforma',
                'verbose_name_plural': 'Proformas',
                'ordering': ['-data_emissao'],
            },
        ),
        migrations.CreateModel(
            name='ItensProforma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantidade')),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Preço Unitário')),
                ('subtotal', models.DecimalField(decimal_places=2, editable=False, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Subtotal')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='faturacao.produtos', verbose_name='Produto')),
                ('proforma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='faturacao.proformas', verbose_name='Proforma')),
            ],
            options={
                'verbose_name': 'Item da Proforma',
                'verbose_name_plural': 'Itens da Proforma',
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='faturas',
            index=models.Index(fields=['empresa', 'cliente', 'status'], name='faturacao_f_empresa_a33ab1_idx'),
        ),
        migrations.AddIndex(
            model_name='faturas',
            index=models.Index(fields=['data_emissao'], name='faturacao_f_data_em_8bef74_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='produtos',
            unique_together={('empresa', 'codigo')},
        ),
        migrations.AddIndex(
            model_name='proformas',
            index=models.Index(fields=['empresa', 'cliente'], name='faturacao_p_empresa_c2abe9_idx'),
        ),
        migrations.AddIndex(
            model_name='proformas',
            index=models.Index(fields=['data_emissao'], name='faturacao_p_data_em_0a841a_idx'),
        ),
    ]
