# Generated by Django 5.1.7 on 2025-03-24 21:55

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faturacao', '0003_produtos_itensfatura'),
        ('subscriptions', '0002_empresas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proformas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_emissao', models.DateField(verbose_name='Data de Emissão')),
                ('valor_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Valor Total')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='faturacao.clientes', verbose_name='Cliente')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscriptions.empresas', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Proforma',
                'verbose_name_plural': 'Proformas',
                'ordering': ['-data_emissao'],
                'indexes': [models.Index(fields=['empresa', 'cliente'], name='faturacao_p_empresa_c2abe9_idx'), models.Index(fields=['data_emissao'], name='faturacao_p_data_em_0a841a_idx')],
            },
        ),
    ]
