# Generated by Django 5.1.7 on 2025-03-24 21:58

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faturacao', '0004_proformas'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItensProforma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantidade')),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Preço Unitário')),
                ('subtotal', models.DecimalField(decimal_places=2, editable=False, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Subtotal')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='faturacao.produtos', verbose_name='Produto')),
                ('proforma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='faturacao.proformas', verbose_name='Proforma')),
            ],
            options={
                'verbose_name': 'Item da Proforma',
                'verbose_name_plural': 'Itens da Proforma',
                'ordering': ['id'],
            },
        ),
    ]
