# Generated by Django 5.1.7 on 2025-03-24 22:33

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subscriptions', '0002_empresas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quartos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=10, verbose_name='Número do Quarto')),
                ('tipo', models.CharField(choices=[('single', 'Single'), ('double', 'Double'), ('suite', 'Suite'), ('luxo', 'Luxo'), ('familiar', 'Familiar')], max_length=20, verbose_name='Tipo de Quarto')),
                ('preco_por_noite', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Preço por Noite')),
                ('status', models.CharField(choices=[('disponivel', 'Disponível'), ('ocupado', 'Ocupado'), ('manutencao', 'Manutenção')], default='disponivel', max_length=20, verbose_name='Status')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('capacidade', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Capacidade (pessoas)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quartos', to='subscriptions.empresas', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Quarto',
                'verbose_name_plural': 'Quartos',
                'ordering': ['numero'],
                'unique_together': {('empresa', 'numero')},
            },
        ),
    ]
