# Generated by Django 5.1.7 on 2025-03-24 22:47

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
        ('subscriptions', '0002_empresas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mesas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=10, verbose_name='Número da Mesa')),
                ('capacidade', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Capacidade (pessoas)')),
                ('status', models.CharField(choices=[('disponivel', 'Disponível'), ('ocupada', 'Ocupada'), ('reservada', 'Reservada')], default='disponivel', max_length=20, verbose_name='Status')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mesas', to='subscriptions.empresas', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Mesa',
                'verbose_name_plural': 'Mesas',
                'ordering': ['numero'],
                'unique_together': {('empresa', 'numero')},
            },
        ),
    ]
